"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockupPreviewPlugin = mockupPreviewPlugin;
const fs_1 = require("fs");
const path_1 = __importDefault(require("path"));
const fast_glob_1 = __importDefault(require("fast-glob"));
const chokidar_1 = __importDefault(require("chokidar"));
const MOCKUPS_DIR = "src/components/mockups";
const GENERATED_MODULE = "src/.generated/mockup-components.ts";
function mockupPreviewPlugin() {
    let root = "";
    let currentSource = "";
    let watcher = null;
    function getMockupsAbsDir() {
        return path_1.default.join(root, MOCKUPS_DIR);
    }
    function getGeneratedModuleAbsPath() {
        return path_1.default.join(root, GENERATED_MODULE);
    }
    function isMockupFile(absolutePath) {
        const rel = path_1.default.relative(getMockupsAbsDir(), absolutePath);
        return (!rel.startsWith("..") && !path_1.default.isAbsolute(rel) && rel.endsWith(".tsx"));
    }
    function isPreviewTarget(relativeToMockups) {
        return relativeToMockups
            .split(path_1.default.sep)
            .every((segment) => !segment.startsWith("_"));
    }
    async function discoverComponents() {
        const files = await (0, fast_glob_1.default)(`${MOCKUPS_DIR}/**/*.tsx`, {
            cwd: root,
            ignore: ["**/_*/**", "**/_*.tsx"],
        });
        return files.map((f) => ({
            globKey: "./" + f.slice("src/".length),
            importPath: path_1.default.posix.relative("src/.generated", f),
        }));
    }
    function generateSource(components) {
        const entries = components
            .map((c) => `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`)
            .join(",\n");
        return [
            "// This file is auto-generated by mockupPreviewPlugin.ts.",
            "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
            "export const modules: ModuleMap = {",
            entries,
            "};",
            "",
        ].join("\n");
    }
    function shouldAutoRescan(pathname) {
        return (pathname.includes("/components/mockups/") ||
            pathname.includes("/.generated/mockup-components"));
    }
    let refreshInFlight = false;
    let refreshQueued = false;
    async function refresh() {
        if (refreshInFlight) {
            refreshQueued = true;
            return false;
        }
        refreshInFlight = true;
        let changed = false;
        try {
            const components = await discoverComponents();
            const newSource = generateSource(components);
            if (newSource !== currentSource) {
                currentSource = newSource;
                const generatedModuleAbsPath = getGeneratedModuleAbsPath();
                (0, fs_1.mkdirSync)(path_1.default.dirname(generatedModuleAbsPath), { recursive: true });
                (0, fs_1.writeFileSync)(generatedModuleAbsPath, currentSource);
                changed = true;
            }
        }
        finally {
            refreshInFlight = false;
        }
        if (refreshQueued) {
            refreshQueued = false;
            const followUp = await refresh();
            return changed || followUp;
        }
        return changed;
    }
    async function onFileAddedOrRemoved() {
        await refresh();
    }
    return {
        name: "mockup-preview",
        enforce: "pre",
        configResolved(config) {
            root = config.root;
        },
        async buildStart() {
            await refresh();
        },
        async configureServer(viteServer) {
            await refresh();
            const mockupsAbsDir = getMockupsAbsDir();
            (0, fs_1.mkdirSync)(mockupsAbsDir, { recursive: true });
            watcher = chokidar_1.default.watch(mockupsAbsDir, {
                ignoreInitial: true,
                awaitWriteFinish: {
                    stabilityThreshold: 100,
                    pollInterval: 50,
                },
            });
            watcher.on("add", (file) => {
                if (isMockupFile(file) &&
                    isPreviewTarget(path_1.default.relative(mockupsAbsDir, file))) {
                    void onFileAddedOrRemoved();
                }
            });
            watcher.on("unlink", (file) => {
                if (isMockupFile(file)) {
                    void onFileAddedOrRemoved();
                }
            });
            viteServer.middlewares.use((req, res, next) => {
                const requestUrl = new URL(req.url ?? "/", "http://127.0.0.1");
                const pathname = requestUrl.pathname;
                const originalEnd = res.end.bind(res);
                res.end = ((...args) => {
                    if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
                        void refresh();
                    }
                    return originalEnd(...args);
                });
                next();
            });
        },
        async closeWatcher() {
            if (watcher) {
                await watcher.close();
            }
        },
    };
}
